const SUPABASE_URL='https://zpgwaesmtlyjyzkxkhgy.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZ3dhZXNtdGx5anl6a3hraGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAzMjU5NDgsImV4cCI6MjEwNTkwMTk0OH0.L50vXjMpfZd4nPtPk53XKn1kvJ6jMsagbOBlpQC3ano';
const IMPACT_PASSWORD='080910';
const fallbackImpact={total_kg:1240,updated_at:'2026-09-25T00:00:00.000Z'};
const impactHeaders={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,Accept:'application/json','Content-Type':'application/json'};
function formatKg(value){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:1}).format(Number(value)||0)+' kg'}
function formatDate(value){return new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeStyle:'short'}).format(new Date(value))}
async function getImpact(){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/impact_data?select=*&order=id.desc&limit=1`,{headers:impactHeaders,cache:'no-store'});if(!response.ok)throw new Error(`Supabase read failed: ${response.status}`);const rows=await response.json();return rows[0]||fallbackImpact}catch(error){console.error(error);return fallbackImpact}}
async function saveImpact(total){const response=await fetch(`${SUPABASE_URL}/rest/v1/impact_data?id=eq.1`,{method:'PATCH',headers:{...impactHeaders,Prefer:'return=representation'},body:JSON.stringify({total_kg:total,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error(`Supabase update failed: ${response.status}`);return (await response.json())[0]}
async function renderImpact(){const impact=await getImpact();document.querySelectorAll('[data-impact-total]').forEach(el=>el.textContent=formatKg(impact.total_kg));document.querySelectorAll('[data-impact-updated]').forEach(el=>el.textContent='Di-update pada '+formatDate(impact.updated_at||impact.updatedAt));return impact}
function mountHomeImpact(impact){const stats=document.getElementById('home-stats');if(!stats)return;const first=stats.querySelector('.stat');if(first){const value=first.querySelector('strong');if(value)value.textContent=formatKg(impact.total_kg);const context=first.querySelector('small');if(context)context.textContent='Di-update pada '+formatDate(impact.updated_at||impact.updatedAt)}const section=stats.parentElement;if(section&&!document.getElementById('impact-update-link')){const note=document.createElement('div');note.className='impact-update-note';note.id='impact-update-link';note.innerHTML='<span data-impact-updated></span><a class="btn outline small" href="update.html">Update data</a>';section.appendChild(note)}}
function mountDashboardImpact(impact){const stats=document.getElementById('dashboard-stats');if(!stats)return;const first=stats.querySelector('.stat');if(first){const value=first.querySelector('strong');if(value)value.textContent=formatKg(impact.total_kg);const context=first.querySelector('small');if(context)context.textContent='Di-update pada '+formatDate(impact.updated_at||impact.updatedAt)}}
function initImpactForm(){const form=document.getElementById('impact-form');if(!form)return;form.addEventListener('submit',async event=>{event.preventDefault();const fields=new FormData(form),message=document.getElementById('impact-message');message.className='form-message error';if(fields.get('password')!==IMPACT_PASSWORD){message.textContent='Kata sandi salah. Silakan coba lagi.';return}const total=Number(fields.get('total'));if(!Number.isFinite(total)||total<0){message.textContent='Masukkan jumlah kilogram yang valid.';return}const button=form.querySelector('button[type=submit]');button.disabled=true;message.textContent='Menyimpan data online...';try{const impact=await saveImpact(total);message.className='form-message';message.textContent='Data berhasil diperbarui dan tersinkron online.';form.reset();await renderImpact();mountHomeImpact(impact);mountDashboardImpact(impact)}catch(error){console.error(error);message.textContent='Data gagal disimpan. Periksa koneksi Supabase dan kebijakan RLS tabel.'}finally{button.disabled=false}})}
async function initImpactWidget(){initImpactForm();const impact=await renderImpact();mountHomeImpact(impact);mountDashboardImpact(impact)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initImpactWidget);else initImpactWidget();